# Generated by Django 3.2.7 on 2021-09-17 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livefeed', '0003_auto_20210917_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handles',
            name='user',
        ),
        migrations.CreateModel(
            name='UserHandlesMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livefeed.handles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
