# Generated by Django 3.2.7 on 2021-09-18 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livefeed', '0004_auto_20210917_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhandlesmap',
            name='handle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='userhandlesmap',
            unique_together={('user', 'handle')},
        ),
        migrations.RemoveField(
            model_name='userhandlesmap',
            name='handles',
        ),
        migrations.DeleteModel(
            name='Handles',
        ),
    ]
